//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STM.ATDB.Model.Transaction
{
    using System;
    
    public partial class AssignWorkShiftByEmp
    {
        public System.DateTime ProdDate { get; set; }
        public string EmpCode { get; set; }
        public string EmpName { get; set; }
        public string ShiftCode { get; set; }
        public string ShiftName { get; set; }
        public string UpdateBy { get; set; }
        public System.DateTime UpdateDate { get; set; }
    }
}
