//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STM.ATDB.Model.Transaction
{
    using System;
    
    public partial class EmployeeSetting
    {
        public string EmpCode { get; set; }
        public string EmpName { get; set; }
        public string EmpStatus { get; set; }
        public string DisplayStatus { get; set; }
        public string UserStatus { get; set; }
        public Nullable<System.DateTime> TransferDate { get; set; }
        public string DivName { get; set; }
        public string DeptName { get; set; }
        public string SecName { get; set; }
        public Nullable<System.DateTime> ResignDate { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
