//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STM.ATDB.Model.Transaction
{
    using System;
    
    public partial class FixOrgEmp
    {
        public string EmpCode { get; set; }
        public string EmpName { get; set; }
        public System.DateTime EffectiveDateFrom { get; set; }
        public System.DateTime EffectiveDateTo { get; set; }
        public string OrgCode { get; set; }
        public string DivCodeKey { get; set; }
        public string DivName { get; set; }
        public string DeptCodeKey { get; set; }
        public string DeptName { get; set; }
        public string SecCodeKey { get; set; }
        public string SecName { get; set; }
        public string UpdateBy { get; set; }
        public System.DateTime UpdateDate { get; set; }
    }
}
