//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STM.ATDB.Model.Transaction
{
    using System;
    
    public partial class GetDepartmentComboResult
    {
        public string DeptCode { get; set; }
        public string DeptCodeDisplay { get; set; }
        public string DeptName { get; set; }
    }
}
