//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STM.ATDB.Model.Common
{
    using System;
    
    public partial class SectionCombo
    {
        public string SecCode { get; set; }
        public string SecName { get; set; }
        public string SecCodeKey { get; set; }
    }
}
