//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STM.ATDB.MvcWeb.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidateViewModelResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidateViewModelResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("STM.ATDB.MvcWeb.Properties.ValidateViewModelResource", typeof(ValidateViewModelResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not allow to operate delete action because this data is currently use..
        /// </summary>
        public static string CanNotDeleteUsageData {
            get {
                return ResourceManager.GetString("CanNotDeleteUsageData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not operate this action because Company Code is duplicate..
        /// </summary>
        public static string CompanyCodeDuplicate {
            get {
                return ResourceManager.GetString("CompanyCodeDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data not found..
        /// </summary>
        public static string DataNotFound {
            get {
                return ResourceManager.GetString("DataNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อมูลการทำงานแทน.
        /// </summary>
        public static string EmployeeReplaceBarTitle {
            get {
                return ResourceManager.GetString("EmployeeReplaceBarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จำนวนคนที่ทำงานแทน.
        /// </summary>
        public static string EmployeeReplaceBarTotalAmountLabel {
            get {
                return ResourceManager.GetString("EmployeeReplaceBarTotalAmountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อมูลการมาทำงาน.
        /// </summary>
        public static string EmployeeWorkingBarTitle {
            get {
                return ResourceManager.GetString("EmployeeWorkingBarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จำนวนคนทั้งหมด.
        /// </summary>
        public static string EmployeeWorkingBarTotalAmoutLabel {
            get {
                return ResourceManager.GetString("EmployeeWorkingBarTotalAmoutLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จำนวนคนมาทำงาน.
        /// </summary>
        public static string EmployeeWorkingBarWorkingAmountLabel {
            get {
                return ResourceManager.GetString("EmployeeWorkingBarWorkingAmountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จำนวนพนักงานที่มาทำงาน.
        /// </summary>
        public static string EmployeeWorkingPlantAxisTitle {
            get {
                return ResourceManager.GetString("EmployeeWorkingPlantAxisTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อมูลการมาทำงานแยกตามสถานที่.
        /// </summary>
        public static string EmployeeWorkingPlantTitle {
            get {
                return ResourceManager.GetString("EmployeeWorkingPlantTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not operate this action because Plant Name and Location Code is duplicate..
        /// </summary>
        public static string LocationCodeDuplicate {
            get {
                return ResourceManager.GetString("LocationCodeDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not operate this action because Plant Code is duplicate..
        /// </summary>
        public static string PlantCodeDuplicate {
            get {
                return ResourceManager.GetString("PlantCodeDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Code is required..
        /// </summary>
        public static string RequireCompanyCode {
            get {
                return ResourceManager.GetString("RequireCompanyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name is required..
        /// </summary>
        public static string RequireCompanyName {
            get {
                return ResourceManager.GetString("RequireCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Code is required..
        /// </summary>
        public static string RequireLocationCode {
            get {
                return ResourceManager.GetString("RequireLocationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Name is required..
        /// </summary>
        public static string RequireLocationName {
            get {
                return ResourceManager.GetString("RequireLocationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password  is required..
        /// </summary>
        public static string RequirePassword {
            get {
                return ResourceManager.GetString("RequirePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plant Code is required..
        /// </summary>
        public static string RequirePlantCode {
            get {
                return ResourceManager.GetString("RequirePlantCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plant Name is required..
        /// </summary>
        public static string RequirePlantName {
            get {
                return ResourceManager.GetString("RequirePlantName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status is required..
        /// </summary>
        public static string RequireStatus {
            get {
                return ResourceManager.GetString("RequireStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select user for setting permission..
        /// </summary>
        public static string RequireUserIDForSavePermission {
            get {
                return ResourceManager.GetString("RequireUserIDForSavePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name is required..
        /// </summary>
        public static string RequireUserName {
            get {
                return ResourceManager.GetString("RequireUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Type  is required..
        /// </summary>
        public static string RequireUserType {
            get {
                return ResourceManager.GetString("RequireUserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จำนวนพนักงานทั้งหมด.
        /// </summary>
        public static string TotalEmployeePieTitle {
            get {
                return ResourceManager.GetString("TotalEmployeePieTitle", resourceCulture);
            }
        }
    }
}
