//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STM.ATDB.Model.Security
{
    using System;
    using System.Collections.Generic;
    
    public partial class Screen
    {
        public string ScreenCode { get; set; }
        public string ScreenName { get; set; }
        public string ScreenClass { get; set; }
        public Nullable<int> Seq { get; set; }
    }
}
