//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STM.ATDB.Model.Security
{
    using System;
    
    public partial class ScreenPermissionListTreeResult
    {
        public string ScreenCode { get; set; }
        public string ScreenName { get; set; }
        public Nullable<int> ScreenSeq { get; set; }
        public string PermissionCode { get; set; }
        public string PermissionName { get; set; }
        public Nullable<int> PermissionSeq { get; set; }
        public Nullable<bool> IsHavePermission { get; set; }
    }
}
