//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STM.ATDB.Model.Security
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecurityMapping
    {
        public string UserCode { get; set; }
        public string Role { get; set; }
        public string ScreenCode { get; set; }
        public string PermissionCode { get; set; }
        public string PermissionType { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
