//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STM.ATDB.MvcWeb.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EmployeeSettingViewModelResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmployeeSettingViewModelResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("STM.ATDB.MvcWeb.Resources.EmployeeSettingViewModelResource", typeof(EmployeeSettingViewModelResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string DeptName {
            get {
                return ResourceManager.GetString("DeptName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Status.
        /// </summary>
        public static string DisplayStatus {
            get {
                return ResourceManager.GetString("DisplayStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Division.
        /// </summary>
        public static string DivName {
            get {
                return ResourceManager.GetString("DivName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emp Code.
        /// </summary>
        public static string EmpCode {
            get {
                return ResourceManager.GetString("EmpCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name-Surname.
        /// </summary>
        public static string EmpName {
            get {
                return ResourceManager.GetString("EmpName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resign Date.
        /// </summary>
        public static string ResignDate {
            get {
                return ResourceManager.GetString("ResignDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section.
        /// </summary>
        public static string SecName {
            get {
                return ResourceManager.GetString("SecName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Date.
        /// </summary>
        public static string TransferDate {
            get {
                return ResourceManager.GetString("TransferDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update By.
        /// </summary>
        public static string Updateby {
            get {
                return ResourceManager.GetString("Updateby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Date.
        /// </summary>
        public static string Updatedate {
            get {
                return ResourceManager.GetString("Updatedate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Status.
        /// </summary>
        public static string UserStatus {
            get {
                return ResourceManager.GetString("UserStatus", resourceCulture);
            }
        }
    }
}
