//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STM.ATDB.MvcWeb.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessageListResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageListResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("STM.ATDB.MvcWeb.Resources.MessageListResource", typeof(MessageListResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save data?.
        /// </summary>
        public static string C0001 {
            get {
                return ResourceManager.GetString("C0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete {0}?.
        /// </summary>
        public static string C0002 {
            get {
                return ResourceManager.GetString("C0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password..
        /// </summary>
        public static string E0001 {
            get {
                return ResourceManager.GetString("E0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password is not correct..
        /// </summary>
        public static string E0002 {
            get {
                return ResourceManager.GetString("E0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while {0} data. Please contact System Administrator. Error: {1}.
        /// </summary>
        public static string E0003 {
            get {
                return ResourceManager.GetString("E0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete {0}. Data was deleted by other user..
        /// </summary>
        public static string E0004 {
            get {
                return ResourceManager.GetString("E0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot save {0}. Data was deleted by other user..
        /// </summary>
        public static string E0005 {
            get {
                return ResourceManager.GetString("E0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot update Display Status because already delete emp. EmpCode: {0}.
        /// </summary>
        public static string E0006 {
            get {
                return ResourceManager.GetString("E0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot update User Status because following data is not exist : {0}.
        /// </summary>
        public static string E0007 {
            get {
                return ResourceManager.GetString("E0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add Assign Work Shift by Emp. because already assign on {0}.
        /// </summary>
        public static string E0008 {
            get {
                return ResourceManager.GetString("E0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save success..
        /// </summary>
        public static string I0001 {
            get {
                return ResourceManager.GetString("I0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete success..
        /// </summary>
        public static string I0002 {
            get {
                return ResourceManager.GetString("I0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password success..
        /// </summary>
        public static string I0003 {
            get {
                return ResourceManager.GetString("I0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password success..
        /// </summary>
        public static string I0004 {
            get {
                return ResourceManager.GetString("I0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password success except following inactive user : {0}.
        /// </summary>
        public static string I0005 {
            get {
                return ResourceManager.GetString("I0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data not found..
        /// </summary>
        public static string I0006 {
            get {
                return ResourceManager.GetString("I0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save permission successfully.
        /// </summary>
        public static string I0007 {
            get {
                return ResourceManager.GetString("I0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input {0} From less than {0} To.
        /// </summary>
        public static string W0001 {
            get {
                return ResourceManager.GetString("W0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Reset Password. Please select EmpCode that User Status = Active.
        /// </summary>
        public static string W0002 {
            get {
                return ResourceManager.GetString("W0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot save Go Out Reason. Time From must not less than {0}.
        /// </summary>
        public static string W0003 {
            get {
                return ResourceManager.GetString("W0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot save Go Out Reason. Time To must not more than {0}.
        /// </summary>
        public static string W0004 {
            get {
                return ResourceManager.GetString("W0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot save {0}. {1} From - To is overlap existing data..
        /// </summary>
        public static string W0005 {
            get {
                return ResourceManager.GetString("W0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select data at least 1 record..
        /// </summary>
        public static string W0006 {
            get {
                return ResourceManager.GetString("W0006", resourceCulture);
            }
        }
    }
}
